import { Listing, Brand, Wilaya, Stats } from "@workspace/api-client-react";

export const MOCK_STATS: Stats = {
  totalListings: 12450,
  totalBrands: 45,
  totalWilayas: 58,
  newThisWeek: 842
};

export const MOCK_BRANDS: Brand[] = [
  { name: "Renault", slug: "renault", count: 3200, country: "France" },
  { name: "Peugeot", slug: "peugeot", count: 2850, country: "France" },
  { name: "Volkswagen", slug: "volkswagen", count: 2100, country: "Germany" },
  { name: "Hyundai", slug: "hyundai", count: 1800, country: "South Korea" },
  { name: "Dacia", slug: "dacia", count: 1500, country: "Romania" },
  { name: "Toyota", slug: "toyota", count: 1200, country: "Japan" },
  { name: "Kia", slug: "kia", count: 950, country: "South Korea" },
  { name: "Seat", slug: "seat", count: 800, country: "Spain" },
  { name: "Skoda", slug: "skoda", count: 650, country: "Czech Republic" },
  { name: "Audi", slug: "audi", count: 450, country: "Germany" },
  { name: "Mercedes-Benz", slug: "mercedes-benz", count: 420, country: "Germany" },
  { name: "BMW", slug: "bmw", count: 380, country: "Germany" },
];

export const MOCK_WILAYAS: Wilaya[] = [
  { code: 16, name: "Alger", nameAr: "الجزائر", count: 4500 },
  { code: 31, name: "Oran", nameAr: "وهران", count: 2100 },
  { code: 9, name: "Blida", nameAr: "البليدة", count: 1200 },
  { code: 15, name: "Tizi Ouzou", nameAr: "تيزي وزو", count: 850 },
  { code: 25, name: "Constantine", nameAr: "قسنطينة", count: 800 },
  { code: 19, name: "Sétif", nameAr: "سطيف", count: 750 },
  { code: 6, name: "Béjaïa", nameAr: "بجاية", count: 600 },
  { code: 23, name: "Annaba", nameAr: "عنابة", count: 550 },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 1,
    title: "Renault Clio 4 GT Line 2018",
    brand: "Renault",
    model: "Clio 4",
    year: 2018,
    price: 2450000,
    mileage: 125000,
    fuelType: "Essence",
    transmission: "Manuelle",
    condition: "Très bon état",
    wilaya: "Alger",
    city: "Cheraga",
    description: "Je mets en vente ma Clio 4 GT Line, très propre, aucun frais à prévoir. Peinture d'origine. Entretien à jour.",
    color: "Rouge",
    doors: 5,
    seats: 5,
    power: 90,
    engineSize: "0.9 TCe",
    features: ["Climatisation automatique", "Toit panoramique", "Jantes alliage", "Radar de recul", "Écran tactile"],
    images: [
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&q=80",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80"
    ],
    sellerName: "Amine",
    sellerPhone: "+213 555 12 34 56",
    sellerType: "Particulier",
    isFeatured: true,
    views: 1240,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: 2,
    title: "Volkswagen Golf 7 R-Line",
    brand: "Volkswagen",
    model: "Golf 7",
    year: 2019,
    price: 4200000,
    mileage: 85000,
    fuelType: "Diesel",
    transmission: "Automatique",
    condition: "Très bon état",
    wilaya: "Oran",
    city: "Es Senia",
    description: "Golf 7 R-Line importer d'Allemagne. Toutes options. Carnet d'entretien complet. Pneus neufs.",
    color: "Blanc",
    doors: 5,
    seats: 5,
    power: 150,
    engineSize: "2.0 TDI",
    features: ["Boîte DSG", "Toit ouvrant", "Sièges chauffants", "Cockpit digital", "Camera de recul"],
    images: [
      "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800&q=80",
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80"
    ],
    sellerName: "Garage Auto Premium",
    sellerPhone: "+213 770 98 76 54",
    sellerType: "Professionnel",
    isFeatured: true,
    views: 3421,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString()
  },
  {
    id: 3,
    title: "Hyundai Tucson 2022",
    brand: "Hyundai",
    model: "Tucson",
    year: 2022,
    price: 6800000,
    mileage: 35000,
    fuelType: "Diesel",
    transmission: "Automatique",
    condition: "Neuf",
    wilaya: "Sétif",
    city: "El Eulma",
    description: "Hyundai Tucson presque neuf. Première main. Garantie encore valable.",
    color: "Gris",
    doors: 5,
    seats: 5,
    power: 136,
    engineSize: "1.6 CRDi",
    features: ["Cuir", "Sièges électriques", "Hayon électrique", "Apple CarPlay", "Régulateur de vitesse"],
    images: [
      "https://images.unsplash.com/photo-1633501258671-5fa580ea5098?w=800&q=80",
      "https://images.unsplash.com/photo-1633501258957-c3db11de6e75?w=800&q=80"
    ],
    sellerName: "Karim",
    sellerPhone: "+213 661 22 33 44",
    sellerType: "Particulier",
    isFeatured: false,
    views: 856,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString()
  },
  {
    id: 4,
    title: "Dacia Stepway Techroad",
    brand: "Dacia",
    model: "Sandero Stepway",
    year: 2020,
    price: 2150000,
    mileage: 92000,
    fuelType: "Essence",
    transmission: "Manuelle",
    condition: "Bon état",
    wilaya: "Blida",
    city: "Ouled Yaich",
    description: "Dacia Stepway en bon état général. Quelques égratignures sur le pare-choc. Moteur impeccable.",
    color: "Gris",
    doors: 5,
    seats: 5,
    power: 90,
    engineSize: "0.9 TCe",
    features: ["Écran tactile", "Climatisation", "Bluetooth", "Régulateur de vitesse"],
    images: [
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80",
    ],
    sellerName: "Sofiane",
    sellerPhone: "+213 550 44 55 66",
    sellerType: "Particulier",
    isFeatured: false,
    views: 432,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString()
  },
  {
    id: 5,
    title: "Peugeot 208 Allure",
    brand: "Peugeot",
    model: "208",
    year: 2021,
    price: 3100000,
    mileage: 60000,
    fuelType: "Essence",
    transmission: "Automatique",
    condition: "Très bon état",
    wilaya: "Alger",
    city: "Hydra",
    description: "Superbe Peugeot 208 Allure avec boîte automatique. Entretien à jour chez la maison.",
    color: "Jaune",
    doors: 5,
    seats: 5,
    power: 100,
    engineSize: "1.2 PureTech",
    features: ["i-Cockpit", "Phares Full LED", "Jantes 16 pouces", "Apple CarPlay/Android Auto"],
    images: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
    ],
    sellerName: "Yasmine",
    sellerPhone: "+213 771 11 22 33",
    sellerType: "Particulier",
    isFeatured: true,
    views: 1560,
    createdAt: new Date().toISOString()
  }
];

export const CAR_FEATURES = [
  "Climatisation automatique", "Climatisation manuelle", "Direction assistée", 
  "Toit ouvrant", "Toit panoramique", "Sièges en cuir", "Sièges chauffants",
  "Radar de recul", "Caméra de recul", "Caméra 360°", "Jantes en alliage",
  "Phares LED", "Phares Xénon", "Feux de jour", "Vitres électriques",
  "Rétroviseurs électriques", "Écran tactile", "GPS / Navigation",
  "Bluetooth", "Apple CarPlay / Android Auto", "Régulateur de vitesse",
  "Limiteur de vitesse", "Alarme", "ABS", "ESP"
];
